#!/bin/bash
echo This bash script queries https://vaccinespotter.org every minute. 
echo That site is updated each minute, so I have set this this script to only 
echo run every minute. I run it from a terminal.
echo   
echo You need to install jq.
echo On a mac it is simply brew install jq
echo Other installs are described here https://stedolan.github.io/jq/download/
echo
echo You need a notifier. I used terminal-notifier. On a mac the command is:
echo brew install terminal-notifier
echo For more information: https://github.com/julienXX/terminal-notifier
echo
echo This is currently set for Colorado and 30 miles. You can change the reference latitude,
echo longitude, and distance. You can change to another state by changing the curl command to 
echo use a different state. You would also need to change your reference latitude and longitude.
echo If you don not know your coordinates, I recommend using google maps.
echo 
echo https://github.com/kristinemlarson 

#
# Things to set :

# Reference Coordinates  - in degrees
# These are in North Boulder
latref=37.3474
lonref=-122.08403
#  Distance you are willing to drive, in miles
d=30 
# Nominally this variable sets how long it runs.  It 
# will run for an hour (60*60 seconds) before stopping
# Change this is if you want to run it longer.
# control C when you want to stop it manually 
x=3600

finished=false
while [ "$finished" = false ]
do
  # clean up
  rm -f toscreen tmp.txt
  echo $x seconds
  curl -s https://www.vaccinespotter.org/api/v0/states/CA.json  | jq -c '.features[] | "\(.geometry.coordinates[0]), \(.geometry.coordinates[1]), \(.properties.provider_brand), \(.properties.city), \(.properties.url), \(.properties.postal_code), \(.properties.appointments_available)" ' | grep true  > tmp.txt
  cat tmp.txt | sed 's/"//g' | awk -F, -v d=$d -v lo=$lonref -v la=$latref '{if (68.2*sqrt(($1-lo)*($1-lo) + ($2-la)*($2-la))< d) print $3, $4, $6, $5, 68.2*sqrt(($1-lo)*($1-lo) + ($2-la)*($2-la)), "miles"}'   > toscreen
  cat toscreen

  # subtract 60 seconds to our simple time variable 
  x=$(( $x - 60 ))

  # check to see if any appointments were caught
  wc=`cat toscreen | wc -l`
  # send the alert using terminal-notifier
  if [ $wc -ne 0 ]; then
    terminal-notifier -title '💰' -message 'Vaccine appointment available!' -sound default
  fi
  if [ $x -lt 0 ]; then
    finished=true
  fi
  # only check every minute
  sleep 60 
  # clean up
  rm -f toscreen tmp.txt
done

